language: php

php:
  - "5.6"
  - "7.0"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=./build/logs/clover.xml

after_success:
  - travis_retry composer require satooshi/php-coveralls ~0.6
  - php vendor/bin/coveralls -v
