services:
  composer:
    build:
      context: .
      target: composer
    volumes:
      - .:/app
    profiles:
      - utils
  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
    profiles:
      - utils
